server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/light?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
#    url: jdbc:mysql://8.130.142.11:3307/light?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    prefix: classpath:/templates
    cache: false

  activemq:
    broker-url: tcp://127.0.0.1:61616
#    broker-url: tcp://8.130.142.11:61617
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 500
      idle-timeout: 30000s
    in-memory: true

  jms:
    pub-sub-domain: true

